name: gamengine
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  vector_math: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:


